In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn import datasets, svm, metrics

In [9]:
digits = load_digits()

In [29]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.15, random_state = 42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1527, 64)
(270, 64)
(1527,)
(270,)


In [22]:
param_C = 100
param_gamma = 0.0001
model = svm.SVC(C=param_C,gamma=param_gamma)

In [23]:
model.fit(X_train, y_train)

SVC(C=100, gamma=0.0001)

In [26]:
expected = y_test 
predicted = model.predict(X_test)

In [27]:
print(metrics.classification_report(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        26
           3       0.96      0.96      0.96        24
           4       1.00      1.00      1.00        37
           5       0.94      1.00      0.97        33
           6       1.00      1.00      1.00        30
           7       1.00      0.96      0.98        26
           8       0.95      0.95      0.95        19
           9       0.97      0.94      0.96        34

    accuracy                           0.98       270
   macro avg       0.98      0.98      0.98       270
weighted avg       0.98      0.98      0.98       270



In [28]:
cm = metrics.confusion_matrix(expected, predicted)
print(cm)

[[23  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0]
 [ 0  0  0 23  0  1  0  0  0  0]
 [ 0  0  0  0 37  0  0  0  0  0]
 [ 0  0  0  0  0 33  0  0  0  0]
 [ 0  0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  1]
 [ 0  0  0  0  0  1  0  0 18  0]
 [ 0  0  0  1  0  0  0  0  1 32]]
